config/routes.rb
Meetmemailer::Application.routes.draw do
  resources :compaigns do
    resources :tasks do
      member do
        get :preview
      end
    end
    member do
      get :execute
    end
  end

  resources :templates

  resources :mailconfigs

  root :to => 'compaigns#index'

end

app/models/compaign.rb
class Compaign < ActiveRecord::Base
  attr_accessible :mailconfig_id, :interval_max, :interval_min, :status, :title

  has_many :tasks
  belongs_to :mailconfig
end

app/controllers/compaigns_controller.rb
require 'maildelivery'

class CompaignsController < ApplicationController
  # GET /compaigns
  # GET /compaigns.json
  def index
    @compaigns = Compaign.paginate(:page => params[:page], :per_page => 10 )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @compaigns }
    end
  end

  # GET /compaigns/1
  # GET /compaigns/1.json
  def show
    @compaign = Compaign.find(params[:id])
    @tasks = @compaign.tasks.paginate(:page => params[:page], :per_page => 10)
    #binding.pry
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @compaign }
    end
  end

  # GET /compaigns/new
  # GET /compaigns/new.json
  def new
    @compaign = Compaign.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @compaign }
    end
  end

  # GET /compaigns/1/edit
  def edit
    @compaign = Compaign.find(params[:id])
  end

  # POST /compaigns
  # POST /compaigns.json
  def create
    #binding.pry
    @compaign = Compaign.new(params[:compaign])
    @compaign.status = 'initial'
    if params[:maillist] == nil
      flash[:notice] = "Please submit tasks excel file."
      render :new and return
    end

    maillist_io = params[:maillist]
    # # binding.pry
    File.open("tmp/#{maillist_io.original_filename}", 'wb') do |file|
      file.write maillist_io.read
    end
    # binding.pry
    oo = Roo::Excelx.new("tmp/#{maillist_io.original_filename}")
    oo.default_sheet = oo.sheets.first
    #binding.pry
    if oo.column('B').index('zh') != nil && (params[:zhtemplate] == nil || params[:zhsubject] == nil)
      flash[:notice] = "Please submit zh template."
      render :new and return
    elsif oo.column('B').index('en') != nil && (params[:entemplate] == nil || params[:ensubject] == nil)
      flash[:notice] = "Please submit en template."
      render :new and return
    end
    zhtemplatefile, zhtemplate = nil
    if params[:zhtemplate] != nil && params[:zhsubject] != nil
      zhtemplatefile = params[:zhtemplate]
      zhtemplate = Template.new
      zhtemplate.lang = "zh"
      zhtemplate.content = zhtemplatefile.read
      zhtemplate.content_type = 'text/html; charset=UTF-8'
      zhtemplate.subject = params[:zhsubject]
      zhtemplate.save
    end
    entemplatefile, entemplate = nil
    if params[:entemplate] != nil && params[:ensubject] != nil
      entemplatefile = params[:entemplate]
      entemplate = Template.new
      entemplate.lang = "en"
      entemplate.content = entemplatefile.read
      entemplate.content_type = 'text/html; charset=UTF-8'
      entemplate.subject = params[:ensubject]
      entemplate.save
    end
    1.upto(oo.last_row) do |line|
      task = Task.new
      task.from = @compaign.mailconfig.user_name
      task.to = oo.cell(line, 'A')
      case oo.cell(line, 'B')
      when 'zh'
        task.template = zhtemplate
      when 'en'
        task.template = entemplate
      end
      task.compaign = @compaign
      task.status = "initial"
      task.save
    end
    #binding.pry
    respond_to do |format|
      if @compaign.save
        format.html { redirect_to @compaign, notice: 'Compaign was successfully created.' }
        format.json { render json: @compaign, status: :created, location: @compaign }
      else
        format.html { render action: "new" }
        format.json { render json: @compaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /compaigns/1
  # PUT /compaigns/1.json
  def update
    @compaign = Compaign.find(params[:id])

    respond_to do |format|
      if @compaign.update_attributes(params[:compaign])
        format.html { redirect_to @compaign, notice: 'Compaign was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @compaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compaigns/1
  # DELETE /compaigns/1.json
  def destroy
    @compaign = Compaign.find(params[:id])
    @compaign.tasks.each do |task|
      task.destroy
    end
    @compaign.destroy

    respond_to do |format|
      format.html { redirect_to compaigns_url }
      format.json { head :no_content }
    end
  end

  def execute
    @compaign = Compaign.find(params[:id])
    @compaign.tasks.each do |task|
      Resque.enqueue(Maildelivery, @compaign.mailconfig_id, task.id)
    end
    redirect_to @compaign, notice: 'Compaign was executing.'
  end
end

app/helpers/compaigns_helper.rb
module CompaignsHelper
end

app/views/compaigns/_form.html.erb
<%= form_for @compaign, :html => { :multipart => true, :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :mailconfig, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :mailconfig_id, Mailconfig.all, :id, :nameoption %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :interval_min, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :interval_min, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :interval_max, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :interval_max, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag :maillist, t("helpers.label.compaign.maillist"), :class => 'control-label' %>
    <div class="controls">
      <%= file_field_tag :maillist, :class => 'input-file' %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag :zhsubject, t("helpers.label.compaign.zhsubject"), :class => 'control-label' %>
    <div class="controls">
      <%= text_field_tag :zhsubject, nil, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag :zhtemplate, t("helpers.label.compaign.zhtemplate"), :class => 'control-label' %>
    <div class="controls">
      <%= file_field_tag :zhtemplate, :class => 'input-file' %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag :ensubject, t("helpers.label.compaign.ensubject"), :class => 'control-label' %>
    <div class="controls">
      <%= text_field_tag :ensubject, nil, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag :entemplate, t("helpers.label.compaign.entemplate"), :class => 'control-label' %>
    <div class="controls">
      <%= file_field_tag :entemplate, :class => 'input-file' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                compaigns_path, :class => 'btn' %>
  </div>
<% end %>

app/views/compaigns/edit.html.erb
<%- model_class = @compaign.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/compaigns/index.html.erb
<%- model_class = Compaign.new.class -%>
<div class="page-header">
  <h1><%=t "compaign" %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= t "helpers.label.compaign.title" %></th>
      <th><%= t "helpers.label.compaign.interval_min" %></th>
      <th><%= t "helpers.label.compaign.interval_max" %></th>
      <th><%= t "helpers.label.compaign.status" %></th>
      <th><%= t "helpers.label.compaign.created_at" %></th>
      <th><%= t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @compaigns.each do |compaign| %>
      <tr>
        <td><%= compaign.id %></td>
        <td><%= link_to compaign.title, compaign_path(compaign) %></td>
        <td><%= compaign.interval_min %></td>
        <td><%= compaign.interval_max %></td>
        <td><%= compaign.status %></td>
        <td><%=l compaign.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_compaign_path(compaign), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      compaign_path(compaign),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @compaigns %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_compaign_path,
            :class => 'btn btn-primary' %>

app/views/compaigns/new.html.erb
<% if flash[:notice] %>
<div class="alert alert-error">
  <%= flash[:notice] %>
</div>
<% end %>
<%- model_class = @compaign.class -%>
<div class="page-header">
  <h1>
    <%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}") %>
  </h1>
</div>
<%= render :partial => 'form' %>

app/views/compaigns/show.html.erb
<% if flash[:notice] %>
<div class="alert alert-success">
  <%= flash[:notice] %>
</div>
<% end %>
<%- model_class = @compaign.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @compaign.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:interval_min) %>:</strong></dt>
  <dd><%= @compaign.interval_min %></dd>
  <dt><strong><%= model_class.human_attribute_name(:interval_max) %>:</strong></dt>
  <dd><%= @compaign.interval_max %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @compaign.status %></dd>
</dl>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>To</th>
      <th>Subject</th>
      <th>Status</th>      
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= task.id %></td>
      <td><%= link_to task.to, compaign_task_path(@compaign, task) %></td>
      <td><%= task.template.subject %></td>
      <td><%= task.status %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @tasks %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              compaigns_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_compaign_path(@compaign), :class => 'btn' %>
  <%= link_to "execute", execute_compaign_path(@compaign), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              compaign_path(@compaign),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>