config/routes.rb
Meetmemailer::Application.routes.draw do
  resources :compaigns do
    resources :tasks do
      member do
        get :preview
      end
    end
    member do
      get :execute
    end
  end

  resources :templates

  resources :mailconfigs

  root :to => 'compaigns#index'

end

app/views/templates/_form.html.erb
<%= form_for @template, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :lang, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lang, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :content_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                templates_path, :class => 'btn' %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<%- model_class = @template.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/templates/index.html.erb
<%- model_class = Template.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:lang) %></th>
      <th><%= model_class.human_attribute_name(:content_type) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @templates.each do |template| %>
      <tr>
        <td><%= link_to template.id, template_path(template) %></td>
        <td><%= template.lang %></td>
        <td><%= template.content_type %></td>
        <td><%= template.content %></td>
        <td><%=l template.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_template_path(template), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      template_path(template),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_template_path,
            :class => 'btn btn-primary' %>

app/views/templates/new.html.erb
<%- model_class = @template.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/templates/show.html.erb
<%- model_class = @template.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:lang) %>:</strong></dt>
  <dd><%= @template.lang %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content_type) %>:</strong></dt>
  <dd><%= @template.content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @template.content %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              templates_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_template_path(@template), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              template_path(@template),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>