config/routes.rb
Meetmemailer::Application.routes.draw do
  resources :compaigns do
    resources :tasks do
      member do
        get :preview
      end
    end
    member do
      get :execute
    end
  end

  resources :templates

  resources :mailconfigs

  root :to => 'compaigns#index'

end

app/models/mailconfig.rb
class Mailconfig < ActiveRecord::Base
  attr_accessible :address, :authentication, :delivery_method, :password, :port, :user_name
  has_many :compaigns

  def nameoption
    user_name
  end
end

app/controllers/mailconfigs_controller.rb
class MailconfigsController < ApplicationController
  # GET /mailconfigs
  # GET /mailconfigs.json
  def index
    @mailconfigs = Mailconfig.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mailconfigs }
    end
  end

  # GET /mailconfigs/1
  # GET /mailconfigs/1.json
  def show
    @mailconfig = Mailconfig.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mailconfig }
    end
  end

  # GET /mailconfigs/new
  # GET /mailconfigs/new.json
  def new
    @mailconfig = Mailconfig.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mailconfig }
    end
  end

  # GET /mailconfigs/1/edit
  def edit
    @mailconfig = Mailconfig.find(params[:id])
  end

  # POST /mailconfigs
  # POST /mailconfigs.json
  def create
    @mailconfig = Mailconfig.new(params[:mailconfig])
    @mailconfig.delivery_method = "smtp"
    @mailconfig.authentication = "login"
    respond_to do |format|
      if @mailconfig.save
        format.html { redirect_to @mailconfig, notice: 'Mailconfig was successfully created.' }
        format.json { render json: @mailconfig, status: :created, location: @mailconfig }
      else
        format.html { render action: "new" }
        format.json { render json: @mailconfig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mailconfigs/1
  # PUT /mailconfigs/1.json
  def update
    @mailconfig = Mailconfig.find(params[:id])

    respond_to do |format|
      if @mailconfig.update_attributes(params[:mailconfig])
        format.html { redirect_to @mailconfig, notice: 'Mailconfig was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mailconfig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mailconfigs/1
  # DELETE /mailconfigs/1.json
  def destroy
    @mailconfig = Mailconfig.find(params[:id])
    @mailconfig.destroy

    respond_to do |format|
      format.html { redirect_to mailconfigs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mailconfigs_helper.rb
module MailconfigsHelper
end

app/views/mailconfigs/_form.html.erb
<%= form_for @mailconfig, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :port, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :port, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :user_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :password, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                mailconfigs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/mailconfigs/edit.html.erb
<%- model_class = @mailconfig.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mailconfigs/index.html.erb
<%- model_class = Mailconfig.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:port) %></th>
      <th><%= model_class.human_attribute_name(:password) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @mailconfigs.each do |mailconfig| %>
      <tr>
        <td><%= mailconfig.id %></td>
        <td><%= link_to mailconfig.user_name, mailconfig_path(mailconfig) %></td>
        <td><%= mailconfig.address %></td>
        <td><%= mailconfig.port %></td>
        <td><%= mailconfig.password %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_mailconfig_path(mailconfig), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      mailconfig_path(mailconfig),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_mailconfig_path,
            :class => 'btn btn-primary' %>

app/views/mailconfigs/new.html.erb
<%- model_class = @mailconfig.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mailconfigs/show.html.erb
<%- model_class = @mailconfig.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:delivery_method) %>:</strong></dt>
  <dd><%= @mailconfig.delivery_method %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @mailconfig.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:port) %>:</strong></dt>
  <dd><%= @mailconfig.port %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_name) %>:</strong></dt>
  <dd><%= @mailconfig.user_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @mailconfig.password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:authentication) %>:</strong></dt>
  <dd><%= @mailconfig.authentication %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              mailconfigs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_mailconfig_path(@mailconfig), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              mailconfig_path(@mailconfig),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>